### PR TITLE
added in apt and rosdep update steps

### PR DESCRIPTION
**Pull request by JasonGibson274**
Resolved issue where apt and rosdep not being updated when building container in circle ci.

### CODE REVIEW

**Comment by barulicm** [comment]
What's the current relationship between devel and master? Do you care that devel is 6 behind master including changes to this file?

**Comment by JasonGibson274** [comment]
master is supposed to be code that is guaranteed to work together and should work well. devel is peer reviewed code that has been put together but may have  known issues or bugs, used to combine multiple dependent features updates that are not ready for master but should be tested together, but reviewed before that.

Devel is essentially acting as a master branch right now though.

**Comment by Alescontrela** [comment]
Thoughts on merging devel into master after merging path planner and occupancy grid?

**Comment by JasonGibson274** [comment]
Ugh now that I think about this we are kind of being dumb, we should just have temporary devel branches for specific things, like mapping and path planning.

**Comment by JasonGibson274** [comment]
but yes

**Comment by JasonGibson274** [comment]
@Alescontrela can I get a positive review?

**Pull request merged**
