### PR TITLE
Design document for OpenCV Line Detection

### LINKED ISSUE #564: OpenCV based line detection
AC: Line detection implemented with OpenCV

### PR DESCRIPTION
**Pull request by VAM7686**
# Design document for OpenCV Line Detection

Wrote design document for OpenCV line detection issue.

This PR does the following:
- Has design document for OpenCV line detection issue

Expectation: provides instruction on how to solve issue.

# Self Checklist
- [x] I have formatted my code using `make format`
- [x] I have tested that the new behaviour works

### CODE REVIEW

**Comment by Dallas-D** [comment]
Can you please update your PR to include your new design doc as a link in the READMEs of all the doc folders? Follow the convention/format of the others (this was in the latest push to master).

**Comment by JasonGibson274** [comment]
I would recommend some erosion and dilation after you do your detection. This should help remove some of the smaller noise components that will likely show up.

**Comment by VAM7686** [comment]
> Can you please update your PR to include your new design doc as a link in the READMEs of all the doc folders? Follow the convention/format of the others (this was in the latest push to master).

**Comment by VAM7686** [comment]
I included my design doc as a link in the README of the design document folder and added the morphological transforms in my algorithm to help clean up noise.

**Comment by Dallas-D** [comment]
You should also update the README in the design folder

**Comment by 14nrv** [comment]
hi, perhaps u should use a ROI also

**Review by matthewhannay567 — APPROVED** [review]
Looks good.

**Pull request merged**
