### PR TITLE
Move Tuning Parameters to YAML File

### PR DESCRIPTION
**Pull request by jmschonfeld**
This moves all of the tuning parameters for the line detector and pothole detector algorithms to two external YAML files. One YAML file is tuned for the gazebo simulator in ideal situations. The other YAML file will be tuned to a real-life scenario in non-ideal conditions. Which YAML file to use is specified in the launch file for line detector and pothole detector.

### CODE REVIEW

**Comment by jgkamat** [comment]
@rmkeezer is this failure the igvc_msgs race condition, or just a mistake in the PR? If it's the race condition we should add the hack to build igvc_msgs back (or fix the race condition).

[see the output of this build log](https://271-16996386-gh.circle-artifacts.com/0/tmp/circle-artifacts.rnZw4Il/compile.txt)

**Comment by jmschonfeld** [comment]
The code compiles fine on my VM with no issues, and executes correctly in RViz and Gazebo. The build log fails on files related to the rviz_plugins directory (it looks like), and I know that none of the code I pushed was related to rviz/rviz plugins.

**Comment by jgkamat** [comment]
Yah, this is the race condition we saw a long time ago. It seems like #149 was never fully fixed (just migitated).

**Comment by jgkamat** [comment]
I've rebuilt your build so you get a :white_check_mark:, hopefully we'll fix this issue before anyone sees it agian.

**Comment by dpattison3** [comment]
#149 Fully fixed it at the time, but at the time, we were not building any of the RViz plugins (they didn't compile for other reasons). #173 is the correct solution.
@rmkeezer Be more careful with the code next time.

**Comment by rmkeezer** [comment]
Ah, yeah I added that a long time ago, my bad

**Comment by rmkeezer** [comment]
This is the first step to eliminating magic numbers from our code, good job!

**Pull request merged**
