### PR TITLE
Added QUICK WORKAROUND to make rviz_plugins compile

### PR DESCRIPTION
**Pull request by rmkeezer**
A better solution should be found later

### CODE REVIEW

**Comment by jgkamat** [comment]
Builds are failing on this branch due to a missing dependency on qt4:

https://192-16996386-gh.circle-artifacts.com/0/tmp/circle-artifacts.kdlLQB9/compile.txt

**Comment by rmkeezer** [comment]
I changed the rvizplugins to use Qt5 instead of Qt4 but the error is still here

**Comment by jgkamat** [comment]
https://196-16996386-gh.circle-artifacts.com/0/tmp/circle-artifacts.PdMRjpN/compile.txt

Seems like it's not finding `igvc_msgs/velocity_pair.h`?

Can you see if thats referenced anywhere?

**Comment by rmkeezer** [comment]
Yes it is needed, but it is also referenced by the motor_controller node and that is building fine

**Comment by jgkamat** [comment]
Your repo is a bit behind master, maybe you could merge master into your repo and see if that helps?

**Comment by jgkamat** [comment]
I just reran the build and it passed, if you have any idea why the previous one failed let me know. They should have been exactly the same.

**Comment by rmkeezer** [comment]
igvc_msgs might have built before igvc, but this race condition should've already been fixed

**Pull request merged**
