### PR TITLE
cmake git submodule check, added common problems to readme

### LINKED ISSUE #453: Update build instructions in README
Pretty sure the build instructions are also gonna be outdated.

AC: Updated build instructions in the README.

### LINKED ISSUE #490: Hard to tell that git submodules are not initialized
Because of how dumb git submodules are, it is almost impossible to tell that you are missing git submodules if you are not already aware of them.

AC: Some system to allow people who do a regular `git clone` to be able to solve the problem of missing the `rj-ros-common` git submodule.

### PR DESCRIPTION
**Pull request by oswinso**
# Description

It is very hard to notice that git submodules are missing. When one tries to compile without the `rj-ros-common` git submodule, one gets the error message:
`Could not find a package configuration file provided by "parameter_assertions" with any of the following names` which is not helpful at all in diagnosing the problem.

This PR does the following:
- Adds a `ensure_submodules.cmake` script to cmake which will automatically call `git submodule update --init --recursive` to ensure that `rj-ros-common` is present during a build
- Adds a "common problems" section to the readme, which includes the git submodule problem (although this shouldn't happen anymore)

Fixes #490, fixes #453

# Testing steps (If relevant)
## cmake automatically does `git submodule update --init --recursive`
1. Remove the `external/rj-ros-common` folder with `rm -rf external/rj-ros-common`
2. Remove the build and devel folders (otherwise cmake caching is gonna complain) `rm -rf build devel`
3. Run `catkin_make`

Expectation: Somewhere in the log you'll see a
```
-- Submodule update
Submodule path 'external/rj-ros-common': checked out '4578f74ebf294a470952ce190e3299176f6bdd86'
```
and the `external/rj-ros-common` folder should be present.

# Self Checklist
- [x] I have formatted my code using `make format`
- [x] I have tested that the new behaviour works

### CODE REVIEW

**Comment by jviszlai** [comment]
After following the testing steps the git submodule doesn't get pulled and it still can't build due to missing parameter assertions.

**Comment by oswinso** [comment]
@jviszlai oh fuck the line I can't believe I commented out the line I added lmao. Try again?

**Comment by jviszlai** [comment]
@oswinso Now it seems to fail the first `catkin_make` and succeed on a second `catkin_make`.

**Comment by oswinso** [comment]
Yeah... I realized that if you're not using `ninja` to build then that seems to happen...

It seems like there's no way to have it just work without needing to get the user to run `catkin_make` again, so I've just changed strats to print out "RERUN CATKIN_MAKE" in all caps and bold red font to inform the user.

**Comment by oswinso** [comment]
Cool. Thanks for finding the bug in the PR. I'm gonna merge.

**Pull request merged**
